Repository MatCron/MatCron, pull requests merged in 2024-12, with the labels that each got.

#46 Database Changed from mssql to mysql
  Backend/Backend/Backend.csproj
  Backend/Backend/Program.cs
  Backend/Backend/appsettings.json
  Backend/Backend/db/Dockerfile
  Backend/docker-compose-mac.yml
  Backend/docker-compose-pi.yml
  Backend/docker-compose.yml
Labels: enhancement

#49 Organisation Features is done and ready to integrate
  Backend/Backend/Controllers/OrganisationController.cs
  Backend/Backend/DTOs/Organisation/OrganisationDTO.cs
  Backend/Backend/DTOs/Organisation/OrganisationSummariseResponseDto.cs
  Backend/Backend/Middlewares/JwtMiddleware.cs
  Backend/Backend/Program.cs
  Backend/Backend/Repositories/Interfaces/IOrganisationRepository.cs
  Backend/Backend/Repositories/OrganisationRepository.cs
Labels: Feature

#50 Feature/55974 create mattress table
  Backend/Backend/Controllers/TestController.cs
  Backend/Backend/Entities/ApplicationDbContext.cs
  Backend/Backend/Entities/Group.cs
  Backend/Backend/Entities/LocationMattress.cs
  Backend/Backend/Entities/Log.cs
  Backend/Backend/Entities/LogMattress.cs
  Backend/Backend/Entities/Mattress.cs
  Backend/Backend/Entities/MattressGroup.cs
  Backend/Backend/Entities/Organisation.cs
  Backend/Backend/Entities/RequestOrder.cs
  Backend/Backend/Entities/User.cs
  Backend/Backend/Program.cs
  Backend/Backend/Repositories/MattressTypeRepository.cs
  Backend/Backend/Repositories/OrganisationRepository.cs
  Backend/Backend/Repositories/UserRepository.cs
  Backend/Backend/db/db.sql
Labels: enhancement

#51 patch for application db context foreign key etc
  Backend/Backend/Entities/ApplicationDbContext.cs
  Backend/Backend/db/db.sql
Labels: bug

#53 Patch/organisation api add more views
  Backend/Backend/DTOs/Organisation/OrganisationDTO.cs
  Backend/Backend/Entities/Organisation.cs
  Backend/Backend/Repositories/OrganisationRepository.cs
  Backend/Backend/db/db.sql
Labels: enhancement

#52 Feature/55608 matteress api
  Backend/Backend/Backend.csproj
  Backend/Backend/Common/Converters/MattressConverter.cs
  Backend/Backend/Common/Converters/OrganisationConverter.cs
  Backend/Backend/Controllers/MattressController.cs
  Backend/Backend/DTOs/Mattress/MattressDetailedDto.cs
  Backend/Backend/DTOs/Mattress/MattressDto.cs
  Backend/Backend/Entities/Mattress.cs
  Backend/Backend/Program.cs
  Backend/Backend/Repositories/Interfaces/IMattressRepository.cs
  Backend/Backend/Repositories/MattressRepository.cs
  Backend/Backend/Repositories/OrganisationRepository.cs
Labels: Feature

#56 mattress amended due to overfetching. Hence, created more efficient w…
  Backend/Backend/Common/Converters/MattressConverter.cs
  Backend/Backend/Common/Utilities/JwtUtils.cs
  Backend/Backend/Controllers/TestController.cs
  Backend/Backend/DTOs/Mattress/MattressDetailedDto.cs
  Backend/Backend/DTOs/Mattress/MattressDto.cs
  Backend/Backend/DTOs/Mattress/MattressImportedDto.cs
  Backend/Backend/Entities/ApplicationDbContext.cs
  Backend/Backend/Entities/LocationMattress.cs
  Backend/Backend/Entities/Mattress.cs
  Backend/Backend/Repositories/Interfaces/IMattressRepository.cs
  Backend/Backend/Repositories/MattressRepository.cs
Labels: enhancement

#57 Commented out to make Organisation ID null at the start
  Backend/Backend/Repositories/MattressRepository.cs
Labels: bug

#58 temporary remove the organisation search query as user role is not de…
  Backend/Backend/Repositories/MattressRepository.cs
Labels: bug
