Repository MatCron/MatCron, pull requests merged in 2025-03, with the labels that each got.

#89 Feature/#58135 session setup
  Backend/Backend/Controllers/UserController.cs
  Backend/Backend/Repositories/Interfaces/IUserRepository.cs
  Backend/Backend/Repositories/UserRepository.cs
  Backend/Backend/appsettings.json
  web-app/src/App.js
  web-app/src/components/layout/Sidebar.js
  web-app/src/context/AuthContext.js
  web-app/src/context/DBContext.js
  web-app/src/context/UserContext.js
  web-app/src/pages/Login.js
  web-app/src/services/AuthService.js
Labels: Feature

#91 Notification
  Backend.Testing/Auth Test/EncryptionHelper.cs
  Backend.Testing/Auth Test/RegistrationTest.cs
  Backend.Testing/Backend.Testing.csproj
  Backend.Testing/Mattres Type Test/MatressTypeRepoTest.cs
  Backend.Testing/Mattress_test/MattressRepoTest.cs
  Backend.Testing/Mattress_test/RepoTestSetup.cs
  Backend.Testing/OrgTest/OrgRepoTest.cs
  Backend/Backend/Common/Enums/MattressStatus.cs
  Backend/Backend/Common/Enums/NotificationStatusEnum.cs
  Backend/Backend/Common/Enums/NotificatoinTypeEnum.cs
  Backend/Backend/Controllers/GroupController.cs
  Backend/Backend/Controllers/MattressController.cs
  Backend/Backend/Controllers/NotificationController.cs
  Backend/Backend/DTOs/Notification/NotificationDTO.cs
  Backend/Backend/Entities/ApplicationDbContext.cs
  Backend/Backend/Entities/Mattress.cs
  Backend/Backend/Entities/Notification.cs
  Backend/Backend/Entities/NotificationType.cs
  Backend/Backend/Entities/UserNotification.cs
  Backend/Backend/Program.cs
  Backend/Backend/Repositories/GroupRepository.cs
  Backend/Backend/Repositories/Interfaces/IGroupRepository.cs
  Backend/Backend/Repositories/Interfaces/INotificationRepository.cs
  Backend/Backend/Repositories/MattressRepository.cs
  Backend/Backend/Repositories/NotificationRepository.cs
Labels: Feature

#93 Integration/#58285 users Dashbaord
  Backend/Backend/Backend.csproj
  Backend/Backend/Common/Converters/Converter.cs
  Backend/Backend/Common/Converters/UserConverter.cs
  Backend/Backend/Common/Enums/UserTypeEnum.cs
  Backend/Backend/Common/Enums/VerificationStatus.cs
  Backend/Backend/Common/Utilities/JwtUtils.cs
  Backend/Backend/Controllers/AuthController.cs
  Backend/Backend/Controllers/EmailController.cs
  Backend/Backend/Controllers/UserController.cs
  Backend/Backend/DTOs/Auth/CompleteRegistrationDto.cs
  Backend/Backend/DTOs/Auth/EmailInvitationDto.cs
  Backend/Backend/DTOs/Auth/VerifyEmailResponseDto.cs
  Backend/Backend/DTOs/User/UserDto.cs
  Backend/Backend/Entities/ApplicationDbContext.cs
  Backend/Backend/Entities/Group.cs
  Backend/Backend/Entities/User.cs
  Backend/Backend/Entities/UserVerification.cs
  Backend/Backend/Middlewares/JwtMiddleware.cs
  Backend/Backend/Program.cs
  Backend/Backend/Repositories/AuthRepository.cs
  Backend/Backend/Repositories/EmailService.cs
  Backend/Backend/Repositories/Interfaces/IAuthRepository.cs
  Backend/Backend/Repositories/Interfaces/IEmailService.cs
  Backend/Backend/appsettings.json
  Backend/Backend/db/db.sql
  web-app/package-lock.json
  web-app/package.json
  web-app/src/App.js
  web-app/src/components/layout/Sidebar.js
  web-app/src/context/AuthContext.js
  web-app/src/pages/ConfirmRegistration.js
  web-app/src/pages/Users/InviteUserDialog.js
  web-app/src/pages/Users/UsersPage.js
  web-app/src/services/AuthService.js
  web-app/src/services/UserService.js
Labels: enhancement, Feature

#95 Adding organisation type information into JWT token
  Backend/Backend/Common/Utilities/JwtUtils.cs
Labels: enhancement

#97 Feature/58289 group api history
  Backend/Backend/Controllers/GroupController.cs
  Backend/Backend/Repositories/Interfaces/ILogRepository.cs
  Backend/Backend/Repositories/LogRepository.cs
Labels: Feature

#99 Feature/admin landing page
  .DS_Store
  Backend/Backend/Controllers/GroupController.cs
  Backend/Backend/appsettings.json
  web-app/package-lock.json
  web-app/package.json
  web-app/postcss.config.js
  web-app/src/App.js
  web-app/src/assets/images/Blue and Black Five Step Modern Illustrative 2D Style Business Plan Roadmap Graph (1).png
  web-app/src/assets/images/Soft Blue Modern How To Achieve Goals Instagram Post (4).png
  web-app/src/components/layout/Sidebar.js
  web-app/src/components/ui/button.js
  web-app/src/context/AuthContext.js
  web-app/src/index.css
  web-app/src/lib/utils.js
  web-app/src/pages/LandingPage.js
  web-app/src/pages/MattressDetailsDrawer.js
  web-app/src/pages/MattressPage.js
  web-app/src/pages/MattressType/CreateDPPForm.js
  web-app/src/pages/MattressType/MattressTypeDetailDrawer.js
  web-app/src/pages/MattressType/MattressTypePage.js
  web-app/tailwind.config.js
Labels: enhancement, Feature

#100 Fixed appsettings.json
  Backend/Backend/appsettings.json
Labels: bug

#102 Done access role on validating the user on middleware.
  Backend/Backend/Middlewares/JwtMiddleware.cs
Labels: enhancement, Server

#103 Feature/rotation mattress update api
  Backend/Backend/Common/Enums/LogStatus.cs
  Backend/Backend/DTOs/Mattress/MattressDto.cs
  Backend/Backend/Entities/Mattress.cs
  Backend/Backend/Repositories/MattressRepository.cs
Labels: enhancement, Server

#104 Patch/token unable to retrieve organisation in jwtutills file
  Backend/Backend/Controllers/TestController.cs
  Backend/Backend/Repositories/AuthRepository.cs
Labels: patch, Server

#105 Patch for bugs in linq on fetching data from database
  Backend/Backend/Middlewares/JwtMiddleware.cs
Labels: bug, Server

#106 Fixed for users and organisation entities Issues
  Backend/Backend/Entities/Organisation.cs
  Backend/Backend/Entities/User.cs
  Backend/docker-compose.yml
Labels: bug, patch, Server
